"""
Inference for the tiny character-level GPT trained by `llm_training.py`.
"""

from __future__ import annotations

import argparse
import math
import pickle
import random


def linear_float(x: list[float], weight: list[list[float]]) -> list[float]:
    return [sum(wi * xi for wi, xi in zip(weight_out, x)) for weight_out in weight]


def softmax_float(logits: list[float]) -> list[float]:
    max_val = max(logits)
    exps = [math.exp(val - max_val) for val in logits]
    total = sum(exps)
    return [val / total for val in exps]


def rmsnorm_float(x: list[float]) -> list[float]:
    mean_square = sum(xi * xi for xi in x) / len(x)
    scale = (mean_square + 1e-5) ** -0.5
    return [xi * scale for xi in x]


def gpt_step_float(token_id, pos_id, keys, values, state_dict, config):
    n_layer = config["n_layer"]
    n_embd = config["n_embd"]
    n_head = config["n_head"]
    head_dim = n_embd // n_head

    token_emb = state_dict["wte"][token_id]
    pos_emb = state_dict["wpe"][pos_id]
    x = [tok + pos for tok, pos in zip(token_emb, pos_emb)]
    x = rmsnorm_float(x)

    for layer_idx in range(n_layer):
        x_residual = x
        x = rmsnorm_float(x)
        q = linear_float(x, state_dict[f"layer{layer_idx}.attn_wq"])
        k = linear_float(x, state_dict[f"layer{layer_idx}.attn_wk"])
        v = linear_float(x, state_dict[f"layer{layer_idx}.attn_wv"])
        keys[layer_idx].append(k)
        values[layer_idx].append(v)

        x_attention = []
        for head_idx in range(n_head):
            hs = head_idx * head_dim
            q_head = q[hs : hs + head_dim]
            k_head = [key[hs : hs + head_dim] for key in keys[layer_idx]]
            v_head = [val[hs : hs + head_dim] for val in values[layer_idx]]
            attn_logits = [
                sum(q_head[j] * k_head[t][j] for j in range(head_dim)) / head_dim**0.5
                for t in range(len(k_head))
            ]
            attn_weights = softmax_float(attn_logits)
            head_out = [
                sum(attn_weights[t] * v_head[t][j] for t in range(len(v_head)))
                for j in range(head_dim)
            ]
            x_attention.extend(head_out)

        x = linear_float(x_attention, state_dict[f"layer{layer_idx}.attn_wo"])
        x = [a + b for a, b in zip(x, x_residual)]

        x_residual = x
        x = rmsnorm_float(x)
        x = linear_float(x, state_dict[f"layer{layer_idx}.mlp_fc1"])
        x = [max(0.0, xi) for xi in x]
        x = linear_float(x, state_dict[f"layer{layer_idx}.mlp_fc2"])
        x = [a + b for a, b in zip(x, x_residual)]

    return linear_float(x, state_dict["lm_head"])


def sample_next_token(logits: list[float], temperature: float, top_k: int | None) -> int:
    scaled = [x / temperature for x in logits]

    if top_k is not None and top_k > 0:
        top_ids = sorted(range(len(scaled)), key=lambda idx: scaled[idx], reverse=True)[:top_k]
        top_logits = [scaled[idx] for idx in top_ids]
        top_probs = softmax_float(top_logits)
        return random.choices(top_ids, weights=top_probs)[0]

    probs = softmax_float(scaled)
    return random.choices(range(len(probs)), weights=probs)[0]


def generate_sample(state_dict, config, chars, bos, temperature: float, max_new_tokens: int, top_k: int | None) -> str:
    n_layer = config["n_layer"]
    block_size = config["block_size"]
    itos = {idx: ch for idx, ch in enumerate(chars)}
    token_id = bos
    keys, values = [[] for _ in range(n_layer)], [[] for _ in range(n_layer)]
    sample_chars = []

    limit = min(block_size, max_new_tokens)
    for pos_id in range(limit):
        logits = gpt_step_float(token_id, pos_id, keys, values, state_dict, config)
        token_id = sample_next_token(logits, temperature=temperature, top_k=top_k)
        if token_id == bos:
            break
        sample_chars.append(itos[token_id])

    return "".join(sample_chars)


def parse_args():
    parser = argparse.ArgumentParser(description="Run inference using a trained tiny GPT checkpoint.")
    parser.add_argument("--checkpoint", default="Session-04/llm_checkpoint.pkl", help="Path to checkpoint generated by llm_training.py.")
    parser.add_argument("--samples", type=int, default=30, help="Number of samples to generate.")
    parser.add_argument("--temperature", type=float, default=0.7, help="Sampling temperature (>0).")
    parser.add_argument("--top-k", type=int, default=0, help="Top-k sampling; 0 disables top-k.")
    parser.add_argument("--max-new-tokens", type=int, default=16, help="Max generated tokens per sample.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility.")
    return parser.parse_args()


def main():
    args = parse_args()
    if args.temperature <= 0:
        raise ValueError("--temperature must be > 0.")
    if args.samples <= 0:
        raise ValueError("--samples must be > 0.")
    if args.max_new_tokens <= 0:
        raise ValueError("--max-new-tokens must be > 0.")

    random.seed(args.seed)

    with open(args.checkpoint, "rb") as file:
        checkpoint = pickle.load(file)

    state_dict = checkpoint["state_dict"]
    config = checkpoint["config"]
    chars = checkpoint["chars"]
    bos = checkpoint["bos"]
    top_k = args.top_k if args.top_k > 0 else None

    print("--- inference samples ---")
    for idx in range(args.samples):
        text = generate_sample(
            state_dict=state_dict,
            config=config,
            chars=chars,
            bos=bos,
            temperature=args.temperature,
            max_new_tokens=args.max_new_tokens,
            top_k=top_k,
        )
        print(f"sample {idx + 1:2d}: {text}")


if __name__ == "__main__":
    main()
